services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${ZNY_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ZNY_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ZNY_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$ZNY_POSTGRES_USER -d ZNY_POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    container_name: carteira-zen-app
    environment:
      - PYTHONUNBUFFERED=1
      - ENV_MODE=dev
      - DATABASE_URL=postgresql://${ZNY_POSTGRES_USER}:${ZNY_POSTGRES_PASSWORD}@db:5432/${ZNY_POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    restart: always

  ngrok:
    image: wernight/ngrok
    depends_on:
      - api
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
      NGROK_REGION: us
      NGROK_PORT: api:8000
    ports:
      - "4040:4040"

volumes:
  pgdata:
