[project]
name = "carteirazen"
version = "0.0.1"
description = "Projeto CarteiraZen para FastAPI"
readme = "README.md"
license = "MIT"
authors = [{ name = "Cleber Goulart Nandi", email = "cleber.nandi@gmail.com" }]
requires-python = ">=3.13.3"
dependencies = [
    "fastapi[standard]>=0.115.13",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.0",
    "python-dotenv>=1.1.0",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
    "dynaconf>=3.2.5",
    "sqlalchemy>=2.0.41",
    "psycopg2-binary>=2.9.10",
    "passlib>=1.7.4",
    "pillow>=11.3.0",
    "pyotp>=2.9.0",
    "qrcode>=8.2",
    "python-jose>=3.5.0",
    "bcrypt>=4.3.0",
    "alembic>=1.16.2",
]

[project.urls]
Homepage = "https://github.com/CleberNandi/carteiraZen_fastapi"
Documentation = "http://localhost:8000/app/docs"
Repository = "https://github.com/CleberNandi/carteiraZen_fastapi"
Issues = "https://github.com/CleberNandi/carteiraZen_fastapi/issues"
# Changelog = "https://github.com/CleberNandi/carteiraZen_fastapi/blob/master/CHANGELOG.md"

[project.optional-dependencies]
dev = ["ruff", "pyright", "pytest", "pytest-xdist"]

[project.scripts]
# O comando 'carteirazen' executa o app FastAPI
carteirazen = "app.main:app"

# ============================
# Lint e formatação (Ruff)
# ============================
[tool.ruff]
line-length = 119
target-version = "py313"
fix = true
show-fixes = true
indent-width = 4
exclude = ["venv", ".venv", "env", ".env", "node_modules", "__pycache__"]

[tool.ruff.lint]
select = [
    "ASYNC", "A", "ANN", "B", "BLE", "C4", "C90", "COM", "E", "EM", "ERA", "EXE", "F", "FBT", "FIX", "I", "ICN", "ISC", "Q", "RET", "RSE", "S", "SIM", "SLF", "T10", "T20", "TC", "TD", "TRY", "UP", "W", "YTT", "RUF", "N",
]
ignore = ["T201", "COM812"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["ANN201", "S101"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.ruff.lint.isort]
# Ensina ao Ruff qual é o pacote principal do seu projeto.
# Deve ser o mesmo nome da pasta principal.
known-first-party = ["app"]


# ============================
# Tipagem (Pyright)
# ============================
[tool.pyright]
typeCheckingMode = "strict"
pythonVersion = "3.13.3"
include = ["app", "tests"]
exclude = [
    "**/venv", "**/.venv", "**/env", "**/.env", "**/node_modules", "**/__pycache__",
]
venv = ".venv"
venvPath = "."
executionEnvironments = [
  { root = ".", extraPaths = ["app"] }
]

# ============================
# Testes (Pytest)
# ============================
[tool.pytest.ini_options]
pythonpath = ["app"]
testpaths = ["tests"]
asyncio_mode = "auto"
addopts = [
  "--strict-config",
  "--strict-markers",
  "--ignore=docs_src",
  "-s",
  "--color=yes",
  "--tb=short"
]
xfail_strict = true
junit_family = "xunit2"


# ============================
# Build e Setuptools
# ============================
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
]

[tool.setuptools.packages.find]
where = ["app"]

[tool.setuptools]
package-dir = { "" = "app" }
