[default]
ENV = "dev"
PROJECT_NAME = "CarteiraZen"
VERSION = "0.1.0"
BASE_URL = "app"

[dev]
ENV = "dev"
DATABASE_URL = "postgresql+psycopg2://postgres:postgres@localhost:5432/carteirazen_db"

[hml]
ENV = "hml"
DATABASE_URL = "postgresql+psycopg2://postgres:postgres@localhost:5432/carteirazen_db"

[prod]
ENV = "prod"
DATABASE_URL = "postgresql+psycopg2://postgres:postgres@localhost:5432/carteirazen_db"

[test]
ENV = "test"
DATABASE_URL = "sqlite:///./sql_app_test.db"
