"""auth_system_tables

Revision ID: 0078c4a1a68c
Revises: ea91b4f9b522
Create Date: 2025-08-16 16:52:23.755712

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0078c4a1a68c"
down_revision: str | Sequence[str] | None = "ea91b4f9b522"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usuarios", sa.Column("is_verified", sa.Boolean(), nullable=False))
    op.add_column(
        "usuarios",
        sa.Column("verification_token", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "usuarios", sa.Column("failed_login_attempts", sa.Integer(), nullable=False)
    )
    op.add_column(
        "usuarios", sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "usuarios", sa.Column("last_login", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "usuarios",
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usuarios", "password_changed_at")
    op.drop_column("usuarios", "last_login")
    op.drop_column("usuarios", "locked_until")
    op.drop_column("usuarios", "failed_login_attempts")
    op.drop_column("usuarios", "verification_token")
    op.drop_column("usuarios", "is_verified")
    # ### end Alembic commands ###
