"""Auto migration

Revision ID: 0809341760d1
Revises: 3d67da399cfd
Create Date: 2025-07-22 10:54:21.841594

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0809341760d1"
down_revision: str | Sequence[str] | None = "3d67da399cfd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
