"""mensagem

Revision ID: 0af8ddcb2989
Revises:
Create Date: 2025-07-05 08:33:53.068718

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0af8ddcb2989"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
