"""initial migration

Revision ID: 0c5aec068bf4
Revises:
Create Date: 2025-07-05 11:09:25.607200

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c5aec068bf4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("totp_secret", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column("is_2fa_enabled", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    op.create_table(
        "auditoria",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tabela", sa.String(), nullable=False),
        sa.Column("registro_id", sa.Integer(), nullable=False),
        sa.Column("acao", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "data",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("dados_antes", sa.String(), nullable=True),
        sa.Column("dados_depois", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bancos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("codigo", sa.String(), nullable=False),
        sa.Column("ispb", sa.String(), nullable=True),
        sa.Column("cnpj", sa.String(), nullable=True),
        sa.Column("site", sa.String(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bancos_cnpj"), "bancos", ["cnpj"], unique=True)
    op.create_index(op.f("ix_bancos_codigo"), "bancos", ["codigo"], unique=True)
    op.create_index(op.f("ix_bancos_id"), "bancos", ["id"], unique=False)
    op.create_index(op.f("ix_bancos_ispb"), "bancos", ["ispb"], unique=True)
    op.create_index(op.f("ix_bancos_nome"), "bancos", ["nome"], unique=True)
    op.create_table(
        "categorias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("descricao", sa.String(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categorias_id"), "categorias", ["id"], unique=False)
    op.create_table(
        "agencias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("numero", sa.String(length=10), nullable=False),
        sa.Column("digito", sa.String(length=2), nullable=True),
        sa.Column("banco_id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=100), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["banco_id"], ["bancos.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agencias_id"), "agencias", ["id"], unique=False)
    op.create_table(
        "cartoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("numero", sa.String(), nullable=False),
        sa.Column("nome_impresso", sa.String(), nullable=False),
        sa.Column("validade", sa.String(), nullable=False),
        sa.Column("bandeira", sa.String(), nullable=False),
        sa.Column("limite", sa.Integer(), nullable=False),
        sa.Column("banco_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["banco_id"], ["bancos.id"]),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cartoes_id"), "cartoes", ["id"], unique=False)
    op.create_index(
        op.f("ix_cartoes_nome_impresso"), "cartoes", ["nome_impresso"], unique=True
    )
    op.create_index(op.f("ix_cartoes_numero"), "cartoes", ["numero"], unique=True)
    op.create_table(
        "contas_correntes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("numero", sa.String(length=20), nullable=False),
        sa.Column("digito", sa.String(length=2), nullable=True),
        sa.Column("agencia_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "saldo_inicial", sa.Float(), server_default=sa.text("(0.0)"), nullable=False
        ),
        sa.Column(
            "tipo",
            sa.Enum("corrente", "poupanca", name="tipocontaenum"),
            nullable=False,
        ),
        sa.Column("ativo", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["agencia_id"], ["agencias.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contas_correntes_id"), "contas_correntes", ["id"], unique=False
    )
    op.create_table(
        "faturas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cartao_id", sa.Integer(), nullable=False),
        sa.Column("mes", sa.Integer(), nullable=False),
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("valor_total", sa.Float(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["cartao_id"], ["cartoes.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_faturas_id"), "faturas", ["id"], unique=False)
    op.create_table(
        "transacoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("descricao", sa.String(length=255), nullable=False),
        sa.Column("valor", sa.Float(), nullable=False),
        sa.Column("data", sa.DateTime(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum("entrada", "saida", name="tipotransacaoenum"),
            nullable=False,
        ),
        sa.Column(
            "forma_pagamento",
            sa.Enum(
                "pix",
                "debito",
                "dinheiro",
                "boleto",
                "cartao_credito",
                name="formapagamentoenum",
            ),
            nullable=False,
        ),
        sa.Column("conta_origem_id", sa.Integer(), nullable=False),
        sa.Column("categoria_id", sa.Integer(), nullable=False),
        sa.Column("fatura_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["categoria_id"], ["categorias.id"]),
        sa.ForeignKeyConstraint(["conta_origem_id"], ["contas_correntes.id"]),
        sa.ForeignKeyConstraint(["fatura_id"], ["faturas.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transacoes_id"), "transacoes", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transacoes_id"), table_name="transacoes")
    op.drop_table("transacoes")
    op.drop_index(op.f("ix_faturas_id"), table_name="faturas")
    op.drop_table("faturas")
    op.drop_index(op.f("ix_contas_correntes_id"), table_name="contas_correntes")
    op.drop_table("contas_correntes")
    op.drop_index(op.f("ix_cartoes_numero"), table_name="cartoes")
    op.drop_index(op.f("ix_cartoes_nome_impresso"), table_name="cartoes")
    op.drop_index(op.f("ix_cartoes_id"), table_name="cartoes")
    op.drop_table("cartoes")
    op.drop_index(op.f("ix_agencias_id"), table_name="agencias")
    op.drop_table("agencias")
    op.drop_index(op.f("ix_categorias_id"), table_name="categorias")
    op.drop_table("categorias")
    op.drop_index(op.f("ix_bancos_nome"), table_name="bancos")
    op.drop_index(op.f("ix_bancos_ispb"), table_name="bancos")
    op.drop_index(op.f("ix_bancos_id"), table_name="bancos")
    op.drop_index(op.f("ix_bancos_codigo"), table_name="bancos")
    op.drop_index(op.f("ix_bancos_cnpj"), table_name="bancos")
    op.drop_table("bancos")
    op.drop_table("auditoria")
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
