"""Ajuste model cartao2

Revision ID: 0dd8beed3edc
Revises: 22854b1a0860
Create Date: 2025-08-19 10:13:09.777061

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0dd8beed3edc"
down_revision: str | Sequence[str] | None = "22854b1a0860"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cartoes",
        sa.Column("dias_vencimento", sa.Integer(), nullable=True, server_default="10"),
    )
    op.alter_column("cartoes", "dias_vencimento", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cartoes", "dias_vencimento")
    # ### end Alembic commands ###
