"""sync_enabled

Revision ID: 0f91f1f92661
Revises: 62b6bc467abf
Create Date: 2025-08-04 18:29:23.171468

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f91f1f92661"
down_revision: str | Sequence[str] | None = "62b6bc467abf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("sync_enabled", sa.Boolean(), nullable=False, server_default="False"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "sync_enabled")
    # ### end Alembic commands ###
