"""Ajuste model cartao

Revision ID: 22854b1a0860
Revises: da70b9883330
Create Date: 2025-08-19 09:59:09.127137

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22854b1a0860"
down_revision: str | Sequence[str] | None = "da70b9883330"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cartoes", sa.Column("dia_fechamento", sa.Integer(), nullable=True))
    op.execute("UPDATE cartoes SET dia_fechamento = 1")
    op.drop_column("cartoes", "vencimento")
    op.drop_column("cartoes", "fechamento")
    op.add_column(
        "transacoes_parcelas", sa.Column("numero_parcela", sa.Integer(), nullable=False)
    )
    op.add_column(
        "transacoes_parcelas", sa.Column("total_parcelas", sa.Integer(), nullable=False)
    )
    op.add_column(
        "transacoes_parcelas", sa.Column("valor_cents", sa.BigInteger(), nullable=False)
    )
    op.add_column(
        "transacoes_parcelas", sa.Column("data_vencimento", sa.Date(), nullable=False)
    )
    op.add_column(
        "transacoes_parcelas", sa.Column("paga", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "transacoes_parcelas", sa.Column("cancelada", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "transacoes_parcelas", sa.Column("fatura_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "transacoes_parcelas",
        sa.Column("fatura_pagamento_id", sa.Integer(), nullable=True),
    )
    op.alter_column(
        "cartoes", "dia_fechamento", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "transacoes_parcelas",
        "transacao_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.create_foreign_key(None, "transacoes_parcelas", "faturas", ["fatura_id"], ["id"])
    op.create_foreign_key(
        None,
        "transacoes_parcelas",
        "faturas_pagamentos",
        ["fatura_pagamento_id"],
        ["id"],
    )
    op.drop_column("transacoes_parcelas", "quantidade")
    op.drop_column("transacoes_parcelas", "parcela_inicial")
    op.drop_column("transacoes_parcelas", "periodicidade")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transacoes_parcelas",
        sa.Column(
            "periodicidade", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "transacoes_parcelas",
        sa.Column("parcela_inicial", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "transacoes_parcelas",
        sa.Column("quantidade", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "transacoes_parcelas", type_="foreignkey")
    op.drop_constraint(None, "transacoes_parcelas", type_="foreignkey")
    op.alter_column(
        "transacoes_parcelas", "transacao_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("transacoes_parcelas", "fatura_pagamento_id")
    op.drop_column("transacoes_parcelas", "fatura_id")
    op.drop_column("transacoes_parcelas", "cancelada")
    op.drop_column("transacoes_parcelas", "paga")
    op.drop_column("transacoes_parcelas", "data_vencimento")
    op.drop_column("transacoes_parcelas", "valor_cents")
    op.drop_column("transacoes_parcelas", "total_parcelas")
    op.drop_column("transacoes_parcelas", "numero_parcela")
    op.add_column(
        "cartoes",
        sa.Column("fechamento", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "cartoes",
        sa.Column("vencimento", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.drop_column("cartoes", "dias_vencimento")
    op.drop_column("cartoes", "dia_fechamento")
    # ### end Alembic commands ###
