"""Auto migration

Revision ID: 296ea2e18f4c
Revises: 0f91f1f92661
Create Date: 2025-08-05 13:55:50.944504

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "296ea2e18f4c"
down_revision: str | Sequence[str] | None = "0f91f1f92661"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
