"""empty message

Revision ID: 3d67da399cfd
Revises: 8a4860fa0832
Create Date: 2025-07-21 18:21:35.598770

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d67da399cfd"
down_revision: str | Sequence[str] | None = "8a4860fa0832"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auditoria", sa.Column("dados_input", sa.String(), nullable=True))
    op.add_column(
        "auditoria",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.create_index(
        op.f("ix_auditoria_created_at"), "auditoria", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auditoria_created_at"), table_name="auditoria")
    op.drop_column("auditoria", "created_at")
    op.drop_column("auditoria", "dados_input")
    # ### end Alembic commands ###
