"""alterando users para duas etapas de signup 3

Revision ID: 3f15fb6ba958
Revises: 529f3812b849
Create Date: 2025-08-11 19:08:14.786098

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f15fb6ba958"
down_revision: str | Sequence[str] | None = "529f3812b849"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bancos", "sync_uuid", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("cartoes", "sync_uuid", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "categorias", "sync_uuid", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("contas", "sync_uuid", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("faturas", "sync_uuid", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "sync_queue", "sync_uuid", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "transacoes", "sync_uuid", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("users", "sync_uuid", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "sync_uuid", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "transacoes", "sync_uuid", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "sync_queue", "sync_uuid", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("faturas", "sync_uuid", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("contas", "sync_uuid", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "categorias", "sync_uuid", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("cartoes", "sync_uuid", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("bancos", "sync_uuid", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
