"""alterando users para duas etapas de signup

Revision ID: 4a9797dd68c3
Revises: 4602b8517eba
Create Date: 2025-08-11 19:05:24.054631

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "4a9797dd68c3"
down_revision: str | Sequence[str] | None = "4602b8517eba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
