"""Auto migration

Revision ID: 5f85a0b58b5b
Revises: 0078c4a1a68c
Create Date: 2025-08-17 20:51:17.412524

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f85a0b58b5b"
down_revision: str | Sequence[str] | None = "0078c4a1a68c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categorias", sa.Column("descricao", sa.Text(), nullable=True))
    op.add_column("categorias", sa.Column("icone", sa.String(length=50), nullable=True))
    op.add_column(
        "categorias", sa.Column("categoria_pai_id", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "categorias", "cor", existing_type=sa.VARCHAR(length=7), nullable=True
    )
    op.alter_column(
        "categorias", "usuario_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_foreign_key(
        None, "categorias", "categorias", ["categoria_pai_id"], ["id"]
    )
    op.drop_column("categorias", "tipo")
    op.add_column("faturas", sa.Column("cartao_id", sa.Integer(), nullable=False))
    op.add_column("faturas", sa.Column("data_fechamento", sa.Date(), nullable=False))
    op.add_column("faturas", sa.Column("data_vencimento", sa.Date(), nullable=False))
    op.add_column(
        "faturas", sa.Column("data_inicio_periodo", sa.Date(), nullable=False)
    )
    op.add_column("faturas", sa.Column("data_fim_periodo", sa.Date(), nullable=False))
    op.add_column("faturas", sa.Column("valor_total", sa.Integer(), nullable=False))
    op.add_column("faturas", sa.Column("valor_pago", sa.Integer(), nullable=False))
    op.add_column("faturas", sa.Column("valor_minimo", sa.Integer(), nullable=False))
    op.add_column("faturas", sa.Column("paga", sa.Boolean(), nullable=False))
    op.add_column("faturas", sa.Column("vencida", sa.Boolean(), nullable=False))
    op.add_column("faturas", sa.Column("juros_mora", sa.Integer(), nullable=True))
    op.add_column("faturas", sa.Column("multa", sa.Integer(), nullable=True))
    op.add_column("faturas", sa.Column("observacoes", sa.Text(), nullable=True))
    op.drop_constraint(
        op.f("faturas_conta_cartao_id_fkey"), "faturas", type_="foreignkey"
    )
    op.create_foreign_key(None, "faturas", "cartoes", ["cartao_id"], ["id"])
    op.drop_column("faturas", "vencimento")
    op.drop_column("faturas", "cor")
    op.drop_column("faturas", "valor_cents")
    op.drop_column("faturas", "pago")
    op.drop_column("faturas", "conta_cartao_id")
    op.drop_column("faturas", "fechamento")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "faturas",
        sa.Column("fechamento", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "faturas",
        sa.Column("conta_cartao_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "faturas", sa.Column("pago", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "faturas",
        sa.Column("valor_cents", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "faturas",
        sa.Column("cor", sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    )
    op.add_column(
        "faturas",
        sa.Column("vencimento", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "faturas", type_="foreignkey")
    op.create_foreign_key(
        op.f("faturas_conta_cartao_id_fkey"),
        "faturas",
        "cartoes",
        ["conta_cartao_id"],
        ["id"],
    )
    op.drop_column("faturas", "observacoes")
    op.drop_column("faturas", "multa")
    op.drop_column("faturas", "juros_mora")
    op.drop_column("faturas", "vencida")
    op.drop_column("faturas", "paga")
    op.drop_column("faturas", "valor_minimo")
    op.drop_column("faturas", "valor_pago")
    op.drop_column("faturas", "valor_total")
    op.drop_column("faturas", "data_fim_periodo")
    op.drop_column("faturas", "data_inicio_periodo")
    op.drop_column("faturas", "data_vencimento")
    op.drop_column("faturas", "data_fechamento")
    op.drop_column("faturas", "cartao_id")
    op.add_column(
        "categorias",
        sa.Column("tipo", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "categorias", type_="foreignkey")
    op.alter_column(
        "categorias", "usuario_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "categorias", "cor", existing_type=sa.VARCHAR(length=7), nullable=False
    )
    op.drop_column("categorias", "categoria_pai_id")
    op.drop_column("categorias", "icone")
    op.drop_column("categorias", "descricao")
    # ### end Alembic commands ###
