"""initial migration

Revision ID: 7e87ddd3e5cf
Revises: 0c5aec068bf4
Create Date: 2025-07-05 11:10:48.718229

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "7e87ddd3e5cf"
down_revision: str | Sequence[str] | None = "0c5aec068bf4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
