"""Ajusta conta, banco_id para null=true

Revision ID: 7e979d5ca948
Revises: 0dd8beed3edc
Create Date: 2025-08-19 11:33:01.512516

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e979d5ca948"
down_revision: str | Sequence[str] | None = "0dd8beed3edc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("contas", "banco_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("contas", "banco_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
