"""is_email_confirmed

Revision ID: 88fade9a723a
Revises: aa7446732810
Create Date: 2025-08-11 18:54:46.948758

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88fade9a723a"
down_revision: str | Sequence[str] | None = "aa7446732810"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_email_confirmed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        "users", sa.Column("email_confirmation_token", sa.String(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("email_token_expires_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_token_expires_at")
    op.drop_column("users", "email_confirmation_token")
    op.drop_column("users", "is_email_confirmed")
    # ### end Alembic commands ###
