"""migration limpa

Revision ID: 90da5d644b34
Revises: c4ed1321f41f
Create Date: 2025-07-21 11:25:44.045777

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90da5d644b34"
down_revision: str | Sequence[str] | None = "c4ed1321f41f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contas_correntes", "nome", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "contas_correntes", "digito", existing_type=sa.VARCHAR(length=2), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contas_correntes", "digito", existing_type=sa.VARCHAR(length=2), nullable=True
    )
    op.alter_column(
        "contas_correntes", "nome", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    # ### end Alembic commands ###
