"""revisando crud e models

Revision ID: a7be8966a6f5
Revises:
Create Date: 2025-07-05 19:31:22.817784

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7be8966a6f5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("agencias", "ativo", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "auditoria",
        "data",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column("bancos", "ativo", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("cartoes", "ativo", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "contas_correntes", "ativo", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "contas_correntes",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "users", "is_2fa_enabled", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "is_2fa_enabled", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "contas_correntes",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "contas_correntes", "ativo", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column("cartoes", "ativo", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("bancos", "ativo", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "auditoria",
        "data",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column("agencias", "ativo", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
