"""criando tabelas iniciais

Revision ID: a97a7d7a0d43
Revises:
Create Date: 2025-08-14 10:34:56.122163

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a97a7d7a0d43"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
