"""sync_queue

Revision ID: aa7446732810
Revises: 296ea2e18f4c
Create Date: 2025-08-05 14:18:53.154988

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "aa7446732810"
down_revision: str | Sequence[str] | None = "296ea2e18f4c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
