"""Alteracao do Contas-correntes incluindo campo nome e deixando outros nullable false

Revision ID: cfb1c942704a
Revises: fc20bae0950f
Create Date: 2025-07-21 11:03:43.269287

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfb1c942704a"
down_revision: str | Sequence[str] | None = "fc20bae0950f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contas_correntes", sa.Column("nome", sa.String(length=100), nullable=False)
    )
    op.alter_column(
        "contas_correntes", "digito", existing_type=sa.VARCHAR(length=2), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contas_correntes", "digito", existing_type=sa.VARCHAR(length=2), nullable=True
    )
    op.drop_column("contas_correntes", "nome")
    # ### end Alembic commands ###
