"""faturas_pagamentos

Revision ID: da70b9883330
Revises: 5f85a0b58b5b
Create Date: 2025-08-17 20:53:22.230766

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da70b9883330"
down_revision: str | Sequence[str] | None = "5f85a0b58b5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "faturas_pagamentos",
        sa.Column("fatura_id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("valor_pago", sa.Integer(), nullable=False),
        sa.Column("data_pagamento", sa.Date(), nullable=False),
        sa.Column("forma_pagamento", sa.String(length=50), nullable=False),
        sa.Column("comprovante", sa.String(length=255), nullable=True),
        sa.Column("observacoes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("sync_uuid", sa.String(), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column("sync_enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["fatura_id"], ["faturas.id"]),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_faturas_pagamentos_id"), "faturas_pagamentos", ["id"], unique=False
    )
    op.drop_index(op.f("ix_pagamentos_faturas_id"), table_name="pagamentos_faturas")
    op.drop_table("pagamentos_faturas")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pagamentos_faturas",
        sa.Column("fatura_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("usuario_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("valor_pago", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("data_pagamento", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "forma_pagamento",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "comprovante", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("observacoes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("ativo", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("origin", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("sync_uuid", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "last_sync_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("sync_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["fatura_id"],
            ["faturas.id"],
            name=op.f("pagamentos_faturas_fatura_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name=op.f("pagamentos_faturas_usuario_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pagamentos_faturas_pkey")),
    )
    op.create_index(
        op.f("ix_pagamentos_faturas_id"), "pagamentos_faturas", ["id"], unique=False
    )
    op.drop_index(op.f("ix_faturas_pagamentos_id"), table_name="faturas_pagamentos")
    op.drop_table("faturas_pagamentos")
    # ### end Alembic commands ###
