"""NFCe Ajuste nome

Revision ID: ea91b4f9b522
Revises: f72d518afec6
Create Date: 2025-08-15 13:58:24.093472

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea91b4f9b522"
down_revision: str | Sequence[str] | None = "f72d518afec6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_itens_notas_fiscais_id"), table_name="itens_notas_fiscais")
    op.drop_table("itens_notas_fiscais")
    op.drop_index(op.f("ix_notas_fiscais_chave_acesso"), table_name="notas_fiscais")
    op.drop_index(op.f("ix_notas_fiscais_cnpj"), table_name="notas_fiscais")
    op.drop_index(op.f("ix_notas_fiscais_id"), table_name="notas_fiscais")
    op.drop_table("notas_fiscais")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notas_fiscais",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('notas_fiscais_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "emitente", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("cnpj", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "endereco", sa.VARCHAR(length=500), autoincrement=False, nullable=False
        ),
        sa.Column(
            "valor_total",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("numero", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("serie", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "data_emissao", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "protocolo", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "chave_acesso", sa.VARCHAR(length=60), autoincrement=False, nullable=False
        ),
        sa.Column(
            "consumidor", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "tributos",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="notas_fiscais_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("ix_notas_fiscais_id"), "notas_fiscais", ["id"], unique=False)
    op.create_index(
        op.f("ix_notas_fiscais_cnpj"), "notas_fiscais", ["cnpj"], unique=False
    )
    op.create_index(
        op.f("ix_notas_fiscais_chave_acesso"),
        "notas_fiscais",
        ["chave_acesso"],
        unique=True,
    )
    op.create_table(
        "itens_notas_fiscais",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("nota_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "descricao", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "quantidade",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "unidade", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "valor_unitario",
            sa.NUMERIC(precision=10, scale=4),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "valor_total",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["nota_id"],
            ["notas_fiscais.id"],
            name=op.f("itens_notas_fiscais_nota_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("itens_notas_fiscais_pkey")),
    )
    op.create_index(
        op.f("ix_itens_notas_fiscais_id"), "itens_notas_fiscais", ["id"], unique=False
    )
    # ### end Alembic commands ###
