"""NFCe

Revision ID: f72d518afec6
Revises: a97a7d7a0d43
Create Date: 2025-08-15 13:52:55.987289

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f72d518afec6"
down_revision: str | Sequence[str] | None = "a97a7d7a0d43"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bancos", sa.Column("origin", sa.String(), nullable=False))
    op.add_column("bancos", sa.Column("sync_uuid", sa.String(), nullable=True))
    op.add_column("bancos", sa.Column("last_sync_at", sa.DateTime(), nullable=True))
    op.add_column("bancos", sa.Column("sync_enabled", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_bancos_id"), "bancos", ["id"], unique=False)
    op.add_column("cartoes", sa.Column("origin", sa.String(), nullable=False))
    op.add_column("cartoes", sa.Column("sync_uuid", sa.String(), nullable=True))
    op.add_column("cartoes", sa.Column("last_sync_at", sa.DateTime(), nullable=True))
    op.add_column("cartoes", sa.Column("sync_enabled", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_cartoes_id"), "cartoes", ["id"], unique=False)
    op.add_column("categorias", sa.Column("origin", sa.String(), nullable=False))
    op.add_column("categorias", sa.Column("sync_uuid", sa.String(), nullable=True))
    op.add_column("categorias", sa.Column("last_sync_at", sa.DateTime(), nullable=True))
    op.add_column("categorias", sa.Column("sync_enabled", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_categorias_id"), "categorias", ["id"], unique=False)
    op.add_column("contas", sa.Column("origin", sa.String(), nullable=False))
    op.add_column("contas", sa.Column("sync_uuid", sa.String(), nullable=True))
    op.add_column("contas", sa.Column("last_sync_at", sa.DateTime(), nullable=True))
    op.add_column("contas", sa.Column("sync_enabled", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_contas_id"), "contas", ["id"], unique=False)
    op.add_column("faturas", sa.Column("origin", sa.String(), nullable=False))
    op.add_column("faturas", sa.Column("sync_uuid", sa.String(), nullable=True))
    op.add_column("faturas", sa.Column("last_sync_at", sa.DateTime(), nullable=True))
    op.add_column("faturas", sa.Column("sync_enabled", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_faturas_id"), "faturas", ["id"], unique=False)
    op.add_column("sub_categorias", sa.Column("origin", sa.String(), nullable=False))
    op.add_column("sub_categorias", sa.Column("sync_uuid", sa.String(), nullable=True))
    op.add_column(
        "sub_categorias", sa.Column("last_sync_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "sub_categorias", sa.Column("sync_enabled", sa.Boolean(), nullable=False)
    )
    op.create_index(
        op.f("ix_sub_categorias_id"), "sub_categorias", ["id"], unique=False
    )
    op.add_column("transacoes", sa.Column("origin", sa.String(), nullable=False))
    op.add_column("transacoes", sa.Column("sync_uuid", sa.String(), nullable=True))
    op.add_column("transacoes", sa.Column("last_sync_at", sa.DateTime(), nullable=True))
    op.add_column("transacoes", sa.Column("sync_enabled", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_transacoes_id"), "transacoes", ["id"], unique=False)
    op.add_column(
        "transacoes_parcelas", sa.Column("origin", sa.String(), nullable=False)
    )
    op.add_column(
        "transacoes_parcelas", sa.Column("sync_uuid", sa.String(), nullable=True)
    )
    op.add_column(
        "transacoes_parcelas", sa.Column("last_sync_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "transacoes_parcelas", sa.Column("sync_enabled", sa.Boolean(), nullable=False)
    )
    op.create_index(
        op.f("ix_transacoes_parcelas_id"), "transacoes_parcelas", ["id"], unique=False
    )
    op.add_column("usuarios", sa.Column("origin", sa.String(), nullable=False))
    op.add_column("usuarios", sa.Column("sync_uuid", sa.String(), nullable=True))
    op.add_column("usuarios", sa.Column("last_sync_at", sa.DateTime(), nullable=True))
    op.add_column("usuarios", sa.Column("sync_enabled", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usuarios", "sync_enabled")
    op.drop_column("usuarios", "last_sync_at")
    op.drop_column("usuarios", "sync_uuid")
    op.drop_column("usuarios", "origin")
    op.drop_index(op.f("ix_transacoes_parcelas_id"), table_name="transacoes_parcelas")
    op.drop_column("transacoes_parcelas", "sync_enabled")
    op.drop_column("transacoes_parcelas", "last_sync_at")
    op.drop_column("transacoes_parcelas", "sync_uuid")
    op.drop_column("transacoes_parcelas", "origin")
    op.drop_index(op.f("ix_transacoes_id"), table_name="transacoes")
    op.drop_column("transacoes", "sync_enabled")
    op.drop_column("transacoes", "last_sync_at")
    op.drop_column("transacoes", "sync_uuid")
    op.drop_column("transacoes", "origin")
    op.drop_index(op.f("ix_sub_categorias_id"), table_name="sub_categorias")
    op.drop_column("sub_categorias", "sync_enabled")
    op.drop_column("sub_categorias", "last_sync_at")
    op.drop_column("sub_categorias", "sync_uuid")
    op.drop_column("sub_categorias", "origin")
    op.drop_index(op.f("ix_faturas_id"), table_name="faturas")
    op.drop_column("faturas", "sync_enabled")
    op.drop_column("faturas", "last_sync_at")
    op.drop_column("faturas", "sync_uuid")
    op.drop_column("faturas", "origin")
    op.drop_index(op.f("ix_contas_id"), table_name="contas")
    op.drop_column("contas", "sync_enabled")
    op.drop_column("contas", "last_sync_at")
    op.drop_column("contas", "sync_uuid")
    op.drop_column("contas", "origin")
    op.drop_index(op.f("ix_categorias_id"), table_name="categorias")
    op.drop_column("categorias", "sync_enabled")
    op.drop_column("categorias", "last_sync_at")
    op.drop_column("categorias", "sync_uuid")
    op.drop_column("categorias", "origin")
    op.drop_index(op.f("ix_cartoes_id"), table_name="cartoes")
    op.drop_column("cartoes", "sync_enabled")
    op.drop_column("cartoes", "last_sync_at")
    op.drop_column("cartoes", "sync_uuid")
    op.drop_column("cartoes", "origin")
    op.drop_index(op.f("ix_bancos_id"), table_name="bancos")
    op.drop_column("bancos", "sync_enabled")
    op.drop_column("bancos", "last_sync_at")
    op.drop_column("bancos", "sync_uuid")
    op.drop_column("bancos", "origin")
    # ### end Alembic commands ###
