"""
This type stub file was generated by pyright.
"""

class Dynaconf:
    ENV: str
    TESTE_CLEBER: str
    PROJECT_NAME: str
    VERSION: str
    DATABASE_URL: str
    BASE_URL: str
    PASSWORD_SYSTEM: str
    SECRET_KEY: str
    ALGORITHM: str
    SMTP_USER: str
    SMTP_PASSWORD: str
    MAIL_FROM: str
    MAIL_FROM_NAME: str
    SMTP_SERVER: str
    SMTP_PORT: str
    ENV_MODE: str
    ZNY_POSTGRES_USER: str
    FRONTEND_URL: str
    JWT_SECRET_KEY: str
    def __init__(self, *args: object, **kwargs: object) -> None: ...
