jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Verify Docker & Compose
        run: docker --version && docker compose version

      - name: Create temp env file for Postgres
        run: |
          #! /bin/bash
          set -e

          # Lista de variáveis obrigatórias
          REQUIRED_VARS=("ZNY_POSTGRES_USER" "ZNY_POSTGRES_PASSWORD" "ZNY_POSTGRES_DB" "DOCKER_USERNAME" "DOCKER_PASSWORD")

          # Checa se cada variável está definida
          for VAR_NAME in "${REQUIRED_VARS[@]}"; do
            VALUE="${{ secrets[$VAR_NAME] }}"
            if [ -z "$VALUE" ]; then
              echo "Error: secret $VAR_NAME is not set!"
              exit 1
            fi
          done

          # Cria o .env.ci
          echo "POSTGRES_USER=${{ secrets.ZNY_POSTGRES_USER }}" > .env.ci
          echo "POSTGRES_PASSWORD=${{ secrets.ZNY_POSTGRES_PASSWORD }}" >> .env.ci
          echo "POSTGRES_DB=${{ secrets.ZNY_POSTGRES_DB }}" >> .env.ci
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env.ci
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> .env.ci

      - name: Print .env.ci for debugging
        run: cat .env.ci

      - name: Run tests with docker compose
        run: docker compose --env-file .env.ci -f docker-compose.ci.yml up --build --abort-on-container-exit --exit-code-from api
