name: CI/CD Zenny

on:
  push:
    branches:
      - "feature/**"
      - "dev"
      - "hml"
      - "main"
  pull_request:
    branches:
      - "dev"
      - "hml"
      - "main"
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Verify Docker & Compose
        run: docker --version && docker compose version

      - name: Create temp env file for Postgres
        env:
          POSTGRES_USER: ${{ secrets.ZNY_POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.ZNY_POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.ZNY_POSTGRES_DB }}
          DATABASE_URL: ${{ secrets.ZNY_DATABASE_URL }}
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
        run: |
          #!/bin/bash
          set -e

          # Checa se cada variável de ambiente está definida
          if [ -z "$SMTP_USER" ]; then
            echo "Error: SMTP_USER is not set!"
            exit 1
          fi

          if [ -z "$SMTP_PASSWORD" ]; then
            echo "Error: SMTP_PASSWORD is not set!"
            exit 1
          fi

          if [ -z "$SECRET_KEY" ]; then
            echo "Error: SECRET_KEY is not set!"
            exit 1
          fi

          if [ -z "$NGROK_AUTHTOKEN" ]; then
            echo "Error: NGROK_AUTHTOKEN is not set!"
            exit 1
          fi

          if [ -z "$POSTGRES_USER" ]; then
            echo "Error: POSTGRES_USER is not set!"
            exit 1
          fi

          if [ -z "$POSTGRES_PASSWORD" ]; then
            echo "Error: POSTGRES_PASSWORD is not set!"
            exit 1
          fi

          if [ -z "$POSTGRES_DB" ]; then
            echo "Error: POSTGRES_DB is not set!"
            exit 1
          fi

          if [ -z "$DOCKER_USERNAME" ]; then
            echo "Error: DOCKER_USERNAME is not set!"
            exit 1
          fi

          if [ -z "$DOCKER_PASSWORD" ]; then
            echo "Error: DOCKER_PASSWORD is not set!"
            exit 1
          fi

          if [ -z "$DATABASE_URL" ]; then
            echo "Error: DATABASE_URL is not set!"
            exit 1
          fi

          # Cria o .env.ci
          set -e
          echo "ZNY_POSTGRES_USER=$secrets.ZNY_POSTGRES_USER" > .env.ci
          echo "ZNY_POSTGRES_PASSWORD=$secrets.ZNY_POSTGRES_PASSWORD" >> .env.ci
          echo "ZNY_POSTGRES_DB=$secrets.ZNY_POSTGRES_DB" >> .env.ci
          echo "ZNY_DATABASE_URL=$secrets.ZNY_DATABASE_URL" >> .env.ci
          echo "SMTP_USER=$secrets.SMTP_USER" >> .env.ci
          echo "SMTP_PASSWORD=$secrets.SMTP_PASSWORD" >> .env.ci
          echo "SECRET_KEY=$secrets.SECRET_KEY" >> .env.ci
          echo "NGROK_AUTHTOKEN=$secrets.NGROK_AUTHTOKEN" >> .env.ci
          echo "DOCKER_USERNAME=$secrets.DOCKER_USERNAME" >> .env.ci
          echo "DOCKER_PASSWORD=$secrets.DOCKER_PASSWORD" >> .env.ci

      - name: Print .env.ci for debugging
        run: cat .env.ci

      - name: Run tests with docker compose
        run: docker compose --env-file .env.ci -f docker-compose.ci.yml up --build --abort-on-container-exit --exit-code-from api

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker image tag
        id: tag
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}" | tr '/' '-')
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "dev" ]]; then
            echo "IMAGE_TAG=dev" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "hml" ]]; then
            echo "IMAGE_TAG=hml" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=feature-${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t clebernandi/carteira-zen-backend:${{ env.IMAGE_TAG }} --target final .

      - name: Push Docker image
        run: |
          docker push clebernandi/carteira-zen-backend:${{ env.IMAGE_TAG }}
